In [1]:
import numpy as np
data = np.array([1,2,3,4,5])
np.mean(data)

3.0

In [2]:
np.median(data)

3.0

In [3]:
np.min(data)

1

In [4]:
np.max(data)

5

In [5]:
std_dev = np.std(data)

In [6]:
print(std_dev)

1.4142135623730951


In [7]:
np.sum(data)

15

In [8]:
reshaped_data = data.reshape((5,1))

In [9]:
print(reshaped_data)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [11]:
concatenated = np.concatenate((array1,array2))

In [12]:
print(concatenated)

[1 2 3 4 5 6]


In [13]:
numbers = np.linspace(0,10,5)

In [14]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [15]:
range_data = np.arange(0,10,2)

In [16]:
print(range_data)

[0 2 4 6 8]
