In [22]:
import numpy as np
data = np.array([1,2,3,4,5])
np.mean(data)

3.0

In [23]:
np.median(data)

3.0

In [24]:
np.min(data)

1

In [25]:
np.max(data)

5

In [26]:
std_dev = np.std(data)

In [29]:
print(std_dev)

1.4142135623730951


In [30]:
np.sum(data)

15

In [34]:
reshaped_data = data.reshape((5,1))

In [35]:
print(reshaped_data)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [36]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [37]:
concatenated = np.concatenate((array1,array2))

In [38]:
print(concatenated)

[1 2 3 4 5 6]


In [52]:
numbers = np.linspace(0,10,5)

In [53]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [55]:
range_data = np.arange(0,10,2)

In [56]:
print(range_data)

[0 2 4 6 8]
